version: "2"

services:
  web:
    image: nginx
    container_name: ups_fee_calculation_web
    working_dir: /usr/share/nginx/html
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports: 
      - 3000:80

  backend:
    image: python:3.7
    container_name: ups_fee_calculation_backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - 10000:10000
    command: bash -c "sleep infinity"

    # -i https://pypi.douban.com/simple/
